version: "3.9"
services:
  app-frontend:
    image: prestoshat-frontend/react:1.0
    container_name: prestoshat
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:80"    