version: "3.9"
services:
  prestoshat-frontend:
    image: mcr.microsoft.com/mcr/prestoshat-frontend
    container_name: prestoshat
    volumes:
      - root:/var/www/html
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:80"

volumes:
  root: