version: "3.9"
services:
  prestoshat-frontend:
    image: prestoshat01.azurecr.io/prestoshat-frontend:0.0.1
    container_name: prestoshat-frontend    
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:80"